require 'base64'

lane :certificates do
  setup_ci if is_ci

  git_url = "git@github.com:lawrence-forooghian/macdown-match.git"
  git_basic_authorization = nil

  if is_ci
    git_url = "https://github.com/lawrence-forooghian/macdown-match.git"
    repository_access_token = ENV["MACDOWN_MATCH_REPOSITORY_ACCESS_TOKEN"]
    git_basic_authorization = Base64.strict_encode64("lawrence-forooghian:#{repository_access_token}")
  end

  match(app_identifier: "com.forooghian.macdown-debug", 
        type: "development", 
        git_url: git_url,
        git_basic_authorization: git_basic_authorization
       )

  match(app_identifier: "com.forooghian.macdown",
        type: "developer_id",
        git_url: git_url,
        git_basic_authorization: git_basic_authorization
       )
end

lane :build_release do
  build_mac_app(
    scheme: "MacDown",
    workspace: "MacDown.xcworkspace",
    export_method: "developer-id",
    export_team_id: "M57TZFTAQ6",
    output_directory: "release",
    export_options: {
      provisioningProfiles: {
        "com.forooghian.macdown" => "match Direct com.forooghian.macdown macos"
      }
    }
  )

  notarize(
    package: "release/MacDown.app",
    api_key_path: "fastlane/AppStoreConnectAPIKey.json",
  )
end

lane :generate_app_store_connect_api_key do
  key = app_store_connect_api_key(
    key_id: "9J42G3U3LV",
    issuer_id: "69a6de90-d3c5-47e3-e053-5b8c7c11a4d1",
    key_filepath: "AuthKey_9J42G3U3LV.p8",
  )

  File.open("AppStoreConnectAPIKey.json", "w") do |f|
    f << key.to_json
  end

  puts("fastlane-compatible App Store Connect API key JSON written to #{File.join(Dir.pwd, "AppStoreConnectAPIKey.json")}")
end
